### ISSUE TITLE
Allow logging to be optional

### ISSUE THREAD

**Issue by MarcDenman** [alhardy/AppMetrics.Reporters#1]
Is there a way to reduce/condense the amount of logs that the InfluxDB reporter produces? 

We have started to make use of it however as we have been debugging our code and looking in our logs it feels like it is providing far too much [information](http://imgur.com/a/PDjuy). 

With the reporter running every 5 seconds and producing 13 debug logs each time we have found it to create a lot of noise.

**Comment by alhardy** [comment]
@MarcDenman at the moment I'm just resolving the `ILoggerFactory` configured in the app where those logs are written as debug level. 

On the `AddReporting` extension method I guess we could allow a separate `LoggerFactory` which you could then set the log level on that to info and write to file separate to your app logs if necessary. Thoughts?

**Comment by MarcDenman** [comment]
Sorry for the delayed response, it has been a crazy week. We have since discovered the "[WithFilte](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging#log-filtering)r" extension method in "Microsoft.Extensions.Logging.Filter" which allows us to set App.Metrics minimum logging level so no changes are needed here. Thank you though :)

**Comment by alhardy** [comment]
@MarcDenman OK cool, FYI I've changed the log level where is makes sense to `Trace` rather than `Info` for the next release
