### ISSUE TITLE
InfluxDb reporter: method not found

### ISSUE THREAD

**Issue by jenyayel** [alhardy/AppMetrics.Reporters#2]
I'm able to run your sample application successfully, but cannot figure out why it cannot report in my application. The settings are identical, same runtime of .NET and latest packages of AppMetrics. Console reporting works well. Did you encounter something similar? Here is stack trace:

```
DEFAULT_APPNAME Error: 0 : [23:52:51:604] [ERR] App.Metrics.Extensions.Reporting.InfluxDB.InfluxDbReporter failed during execution
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Polly.PolicyResult`1<!!0>> Polly.Policy.ExecuteAndCaptureAsync(System.Func`1<System.Threading.Tasks.Task`1<!!0>>, System.Threading.CancellationToken)'.
   at App.Metrics.Extensions.Reporting.InfluxDB.Client.DefaultLineProtocolClient.<WriteAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at App.Metrics.Extensions.Reporting.InfluxDB.Client.DefaultLineProtocolClient.WriteAsync(LineProtocolPayload payload, CancellationToken cancellationToken)
   at App.Metrics.Extensions.Reporting.InfluxDB.InfluxDbReporter.<EndAndFlushReportRunAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at App.Metrics.Reporting.Internal.DefaultReportGenerator.<GenerateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at App.Metrics.Reporting.Internal.Reporter.<>c__DisplayClass14_0.<<ScheduleReport>b__0>d.MoveNext()
```

**Comment by jenyayel** [comment]
@alhardy, in project.json you target Polly 4.3.0 and the same is in .nuspec `<dependency id="Polly" version="4.3.0" />`. However, on nuget.org it states `>=4.3.0`:
![image](https://cloud.githubusercontent.com/assets/1775602/22688337/7201ac3a-ed34-11e6-9dee-ef23c93676ce.png) which cause in my application the following:
![image](https://cloud.githubusercontent.com/assets/1775602/22688368/ac5744da-ed34-11e6-9ce2-ef339b582549.png)

Polly 5.* changed overrides of `ExecuteAndCaptureAsync` method which cause an exception in your timer job.

What cannot understand, why it doesn't use 4.3.0 as it states in your nuspec, and why nuget.org displays that you support 4.3.0 and higher?

**Comment by alhardy** [comment]
@jenyayel I had a quick look around on project.json and nuget docs, I can't see yet that a specific package version can be specified.

I'm guessing that because the dependency is currently set at >= 4.3.0 it's picking up the latest stable version, Polly 5 released a stable version not long ago.

I have been thinking about removing the dependency on Polly and implement a simple circuit breaker/backoff policy myself, just so that there are no external dependencies.

**Comment by jenyayel** [comment]
OK, thanks for the reply. Here is PR #3. 

Do you have any plans for additional reporters?

**Comment by alhardy** [comment]
Fixed by @jenyayel [here](https://github.com/alhardy/AppMetrics.Reporters/commit/113613f050677e0d97c91a6be4b71f94a84e2c32)

**Comment by alhardy** [comment]
@jenyayel I do have plans for additional reporters once a stable version is out which should be in a few weeks hopefully, I'm more keen to look at cross platform solutions using ETW or similar for reporting CPU, memory etc first though.

Re additional reporters I'll probably first start with an Elasticsearch reporter first with some Kibana examples, Graphite is getting a little old now.

**Comment by alhardy** [comment]
Applied patch in [1.0.0-beta5-2](https://www.nuget.org/packages/App.Metrics.Extensions.Reporting.InfluxDB/)

**Comment by jenyayel** [comment]
Thanks.
