### ISSUE TITLE
Console reporter should have an ability to change output formatting 

### ISSUE THREAD

**Issue by jenyayel** [alhardy/AppMetrics.Reporters#27]
Following #19, there should be a way to change format for console similar as in InfluxDB reporter. 

The main reasons for it is that in certain environments (e.g. Heroku) writing metrics and logs into stdout/console and have the environment infrastructure to ship logs and metrics to the data store, will reduce overload from application itself. This, however, requires for the metrics messages to be in the format of the destination store.

**Comment by alhardy** [comment]
Yeah I agree there should be a way to change the format, scheduled for the next alpha realease, but Heroku 👎   :)

**Comment by jenyayel** [comment]
> but Heroku  :-1: :)

It is a long story ;)

**Comment by alhardy** [comment]
haha, yeah I have a few of those :)

**Comment by AmirSasson** [comment]
@alhardy,
the formatting abstraction in the console reporter actually solves some of our reporting problems.
do you have any progress with that?

**Comment by alhardy** [comment]
@AmirSasson no pogress yet, just finished off on a Graphite reporter, I'll be picking this task up in the coming weeks.

**Comment by alhardy** [comment]
See also: https://github.com/alhardy/AppMetrics/issues/143
