### ISSUE TITLE
Review usage of Task.Run

### ISSUE THREAD

**Issue by alhardy** [alhardy/AppMetrics.Reporters#60]
@Alessar I missed this in review before merging, what's the reason for using `Task.Run` in these cases?

- https://github.com/AppMetrics/Reporting/blob/dev/src/App.Metrics.Reporting.Socket/Client/SocketClient.cs#L93
- https://github.com/AppMetrics/Reporting/blob/dev/src/App.Metrics.Reporting.Socket/Client/SocketClient.cs#L93

**Comment by Alessar** [comment]
Maybe it was erratum. Fixed in #61 PR.
