### ISSUE TITLE
Merge App.Metrics.Reporting.Socket and create nuget package for it

### ISSUE THREAD

**Issue by mg-patrickp** [alhardy/AppMetrics.Reporters#64]
Issue :   
https://www.app-metrics.io/reporting/reporters/socket/  states that the package App.Metrics.Reporting.Socket can be installed from Nuget via https://www.nuget.org/packages/App.Metrics.Reporting.Socket/
However, this link is not working.

The corresponding code is available in the dev branch under https://github.com/AppMetrics/Reporting/tree/dev/src/App.Metrics.Reporting.Socket, but not on the master.

Are there any plans to merge the code to the master, and to publish the nuget package?
Or is the code considered as non production ready ?

**Comment by mg-patrickp** [comment]
Thanks a lot for the release !
The sockets package is now available on nuget, so the issue can be closed.

By the way, we are using the sockets reporter in our test environment to send metrics to Telegraf from docker containers, and that's working fine!

**Comment by alhardy** [comment]
Great, thanks to @Alessar
