### ISSUE TITLE
[Graphite] Reporter for Graphite/Carbon DB port 2003 or 2004

### ISSUE THREAD

**Issue by alhardy** [alhardy/AppMetrics.Reporters#8]
Moved here from https://github.com/alhardy/AppMetrics/issues/67

**Comment by nataly87s** [comment]
Hi, we are currently working on a graphite reporter, and will create a PR in the following days

**Comment by alhardy** [comment]
@nataly87s 😎 👍   I can create a new repo for that or you can host the repo under your account?  Im happy either way, this just makes versioning, issue tracking etc a little easier. Let me know.

**Comment by alhardy** [comment]
@nataly87s I've created a [graphite repo](https://github.com/alhardy/AppMetrics.Extensions.Graphite) with the boilerplate if you want to go that way

**Comment by nataly87s** [comment]
@alhardy our current implementation targets version 1.0.0, since that's the version we are running in production. we plan on implementing the spec for 1.1.0 once it reaches stable status

**Comment by alhardy** [comment]
@nataly87s There will be a stable 1.1.0 release around this time next week (week after max). Most of the changes re 1.1.0-alpha were actually around reporting, allowing reporters to share most of the reporting logic, due to this, if possible I'd target 1.1.0 instead, otherwise I'm OK with refactoring the graphite reporter to use 1.1.0 after your PR targeting 1.0.0.

**Comment by alhardy** [comment]
See https://github.com/alhardy/AppMetrics.Extensions.Graphite
